alias sudo='sudo '
alias sudi='sudo -i'
alias nc-u='nc -u -zv'
alias nc-t='nc -t -zv'
alias l='ls -alF'
alias ll='ls -l'
alias la='ls -la'
alias lat='ls -lat'
alias latr='ls -latr'
alias lt='ls -lt'
alias paclog='expac --timefmt="%Y-%m-%d %T" "%l\t%n" | sort | less +G'
alias cdgit='cd ~/git/github.com/jakegiorlando'
alias cdsalt='cd ~/git/github.com/jakegiorlando/unown_srv_salt'

